### ISSUE TITLE
3 ans plus tard Azote n'existe plus, demande de retrait de la limitation d'utilisation

### ISSUE THREAD

**Issue by Antho7900** [Slyker/MultiTool#1]
Salut,

Ayant joué sur azote il y'a plus de 4 ans, j'ai pu bénéficier de ton logiciel de multicompte très spécial en son genre, en essayant de l'utiliser avec officiel je n'ai jamais réussi a cause du message d'erreur

![image](https://user-images.githubusercontent.com/109134479/188173331-19917bfe-0bf5-4a4b-9024-930bff040800.png)

J'ai eu beau chercher sans jamais trouver de logiciel multicompte de la même qualité et avec les mêmes fonctionnalités. Est-ce que tu pourrais lui enlever les limitations relatives a Azote ?

**Comment by Slyker** [comment]
Salut à toi effectivement il ne marchait que sur Azote à l'époque.
Ce projet date vraiment mais je vais voir si je peux faire quelque chose pour toi/vous?

**Comment by Antho7900** [comment]
> Salut à toi effectivement il ne marchait que sur Azote à l'époque. Ce projet date vraiment mais je vais voir si je peux faire quelque chose pour toi/vous ?

Hey, merci pour ta réponse qui nous a redonné espoir, en effet  le projet date et les mises a jour de Dofus se sont succédé depuis que tu l'as codé pour Azote il y'a de cela 4 ans, et pourtant nous avons eu beau chercher parmi les logiciels disponibles actuellement qui font la même chose, je peux t'assurer que le tien les surpasse tous, on ne trouve nul part ailleurs les mêmes options que tu as introduit dans le panel d'options notamment  pour ancrer/désancrer les fenêtres par exemple.

Merci d'avoir accepter de remodifier dans software pour y retirer la modification nous restons dans l'attente de la publication de la nouvelle version. Bien a toi.

**Comment by Antho7900** [comment]
> Salut à toi effectivement il ne marchait que sur Azote à l'époque. Ce projet date vraiment mais je vais voir si je peux faire quelque chose pour toi/vous ?

Hey, est-ce que tu as trouver du temps pour voir si tu peux faire quelque chose ? merci d'avance !

**Comment by Antho7900** [comment]
J'aimerais bien avoir ton contact si possible via une plateforme de communication comme discord

**Comment by Slyker** [comment]
Sly#7785

**Comment by Antho7900** [comment]
> sournois#7785

![image](https://user-images.githubusercontent.com/109134479/197420198-d617e3c8-9eba-481c-b0dc-dd16bee04635.png)


ça n'a spas marché, p-e que tu n'as pas fait gaffe au niveau des caractères spéciaux ou majs chef ?

OK mb je suis con google translate a traduit ton pseudo discord c'est trop mdr
